rolled back changes for xdist handling in vscode as they were not very stable

diff --git a/.github/include/execute_tests/action.yml b/.github/include/execute_tests/action.yml
--- a/.github/include/execute_tests/action.yml
+++ b/.github/include/execute_tests/action.yml
@@ -40,15 +40,37 @@ runs:
         # change to current directory of module            
         cd ./${{ inputs.module }}
         if [[ ${RUNNER_DEBUG} == 1 ]] ; then
-          PYTEST_CMD="uv run pytest --debug "
+          PYTEST_CMD="uv run pytest --debug ${{inputs.pytest_flags}} "
         else
-          PYTEST_CMD="uv run pytest"
+          PYTEST_CMD="uv run pytest ${{inputs.pytest_flags}}"
         fi
-          
-        if ${{ inputs.integration_tests }} ; then
-         $PYTEST_CMD ${{inputs.pytest_flags}}
+
+        if ${{ inputs.test_by_directory }} ; then
+          # Execute tests directory by directory
+          for d in $(find test -type d -exec sh -c 'ls -1 "$1"/*.py >/dev/null 2>&1 && echo "$1"' _ {} \;) ; do
+            if ls "$d"/test_*.py >/dev/null 2>&1 ; then
+              echo "------------------------------------------"
+              echo "Running tests in directory: $d"
+              if ! ${{ inputs.integration_tests }} ; then
+                $PYTEST_CMD -m 'not integrationtest' "$d"/*.py
+              else
+                $PYTEST_CMD "$d"/*.py
+              fi
+              if [ $? -ne 0 ]; then
+                  echo "Tests failed in $d. Stopping."
+                  exit 1
+              fi
+              echo "------------------------------------------"
+              echo ""
+            fi
+          done
         else
-          $PYTEST_CMD ${{inputs.pytest_flags}} -m "not integrationtest"
+          # Execute all tests together
+          if ! ${{ inputs.integration_tests }} ; then
+            $PYTEST_CMD -m 'not integrationtest'
+          else
+            $PYTEST_CMD
+          fi
         fi
 
     - name: Run Safety CLI to check for vulnerabilities
