migrated from poetry to uv

diff --git a/.github/include/test_docker_builds/action.yml b/.github/include/test_docker_builds/action.yml
--- a/.github/include/test_docker_builds/action.yml
+++ b/.github/include/test_docker_builds/action.yml
@@ -18,9 +18,9 @@ runs:
         SHA_TAG=${{ github.sha }}
 
         cd "${module}"
-        echo "Check for [tool.poetry.scripts]"
-        if ! grep -q "^\[tool.poetry.scripts\]" ./pyproject.toml; then
-          echo "Error: [tool.poetry.scripts] section not found in pyproject.toml"
+        echo "Check for [project.scripts]"
+        if ! grep -q "^\[project.scripts\]" ./pyproject.toml; then
+          echo "Error: [project.scripts] section not found in pyproject.toml"
           exit 1
         fi
 
@@ -28,8 +28,8 @@ runs:
 
         # Extract the entrypoint from Dockerfile
         entry_point=$(cat ./Dockerfile | grep "^ENTRYPOINT")
-        if [[ ! "${entry_point}" =~ ^ENTRYPOINT\ \[\"poetry\",\ \"run\",\ \".+\"\]$ ]]; then
-            echo "Error: Entrypoint should be in the format [\"poetry\", \"run\", \"<command>\"]"
+        if [[ ! "${entry_point}" =~ ^ENTRYPOINT\ \[\"uv\",\ \"run\",\ \".+\"\]$ ]]; then
+            echo "Error: Entrypoint should be in the format [\"uv\", \"run\", \"<command>\"]"
             exit 1
         fi
 
@@ -39,7 +39,7 @@ runs:
         command="$(echo "${entry_point}" | awk '{print $4}' | tr -d '",]')"
 
         # check in pyproject if it is a script.
-        script_name=$( grep "^${command} =" ./pyproject.toml)
+        script_name=$(grep -E "^\s*\"${command}.*=" ./pyproject.toml)
         if [[  ! $script_name == *':main"' ]]; then
           # the script is not referencing a main function, must be a module
           echo "Validating if ${command} is a valid module command"
@@ -59,7 +59,7 @@ runs:
           python_module=${main_entry%:*}
           function=${main_entry##*:}
           if [[ -z $main_entry ]]; then
-            echo "Error: Script entry for ${command} not found in [tool.poetry.scripts] section of pyproject.toml "
+            echo "Error: Script entry for ${command} not found in [project.scripts] section of pyproject.toml "
             exit 1
           fi          
         fi
@@ -99,11 +99,11 @@ runs:
             echo "Success:  test folder was not copied to the Docker"
           fi
           
-          poetry run python -m compileall -q /app || (echo "Error: compileall failed" && exit 1)
+          uv run python -m compileall -q /app || (echo "Error: compileall failed" && exit 1)
           if [[ -z $class  ]];then  
             # function is not null, check if the entry in pyproject.toml scripts is valid
-            entry_valid=$(poetry run python -c "import ${python_module} as module;print( '\''${function}'\''  in dir(module))")
-          elif poetry run python -c "from ${python_module} import ${class};  x=${function};" &> /dev/null; then
+            entry_valid=$(uv run python -c "import ${python_module} as module;print( '\''${function}'\''  in dir(module))")
+          elif uv run python -c "from ${python_module} import ${class};  x=${function};" &> /dev/null; then
             entry_valid=True
           fi
           if [ ! "$entry_valid" == "True" ];then
