Creating PR for branch feature/replace_poetry_with_uv (#1538)
* 108b7b1 - Ashwin Krishnan - 2025-02-24 00:35:37 
| debug provided to action
| 
* 02568e5 - Ashwin Krishnan - 2025-02-24 00:25:12 
| debug provided to action
| 
* 19e5e6f - Ashwin Krishnan - 2025-02-24 00:14:44 
| ruff violations fixed
| 
* 0ebee17 - Ashwin Krishnan - 2025-02-24 00:14:19 
| debug provided to action
| 
* c5c465e - Ashwin Krishnan - 2025-02-23 23:13:38 
| added echo stmts to debug
| 
* 01d895b - Ashwin Krishnan - 2025-02-23 23:03:55 
| rollback ruff fix as it was breaking tests
| 
* 5573c9b - Ashwin Krishnan - 2025-02-23 22:50:51 
| attempting to fix the docker static test
| 
* 907a773 - Ashwin Krishnan - 2025-02-23 22:50:24 
| fixed ruff violations
| 
* 6e3020d - Ashwin Krishnan - 2025-02-23 22:27:42 
| rollback ruff fix as it was breaking strawberry
| 
* 4c1f990 - Ashwin Krishnan - 2025-02-23 22:21:29 
| updated docker tests
| 
* ff99bf7 - Ashwin Krishnan - 2025-02-23 22:20:35 
| updated docker tests
| 
* d2dff96 - Ashwin Krishnan - 2025-02-23 22:08:04 
| fixed ruff violations
| 
* 5c7e055 - Ashwin Krishnan - 2025-02-23 22:03:19 
| updated docker tests
| 
* d9c8003 - Ashwin Krishnan - 2025-02-23 21:44:53 
  migrated from poetry to uv

---------

Co-authored-by: Ashwin Krishnan <mkashwin@gmail.com>

diff --git a/.github/include/test_docker_builds/action.yml b/.github/include/test_docker_builds/action.yml
--- a/.github/include/test_docker_builds/action.yml
+++ b/.github/include/test_docker_builds/action.yml
@@ -13,14 +13,17 @@ runs:
     - name: Install dependencies in the
       shell: bash
       run: |
+        if [[ ${RUNNER_DEBUG} == 1 ]] ; then
+          set -x
+        fi
         module=${{ inputs.module }} 
         image_name=${{ inputs.image_name }} 
         SHA_TAG=${{ github.sha }}
 
         cd "${module}"
-        echo "Check for [tool.poetry.scripts]"
-        if ! grep -q "^\[tool.poetry.scripts\]" ./pyproject.toml; then
-          echo "Error: [tool.poetry.scripts] section not found in pyproject.toml"
+        echo "Check for [project.scripts]"
+        if ! grep -q "^\[project.scripts\]" ./pyproject.toml; then
+          echo "Error: [project.scripts] section not found in pyproject.toml"
           exit 1
         fi
 
@@ -28,9 +31,9 @@ runs:
 
         # Extract the entrypoint from Dockerfile
         entry_point=$(cat ./Dockerfile | grep "^ENTRYPOINT")
-        if [[ ! "${entry_point}" =~ ^ENTRYPOINT\ \[\"poetry\",\ \"run\",\ \".+\"\]$ ]]; then
-            echo "Error: Entrypoint should be in the format [\"poetry\", \"run\", \"<command>\"]"
-            exit 1
+        if [[ ! ${entry_point} =~ ^ENTRYPOINT\ \[\"uv\",\ \"run\",\ \".+\"\]$ ]]; then
+          echo 'Error: Entrypoint should be in the format ["uv", "run", "<command>"]'
+          exit 1
         fi
 
         echo "Entrypoint for Docker is: ${entry_point}"
@@ -38,8 +41,14 @@ runs:
         # Extract the command/script name to be run
         command="$(echo "${entry_point}" | awk '{print $4}' | tr -d '",]')"
 
+
         # check in pyproject if it is a script.
-        script_name=$( grep "^${command} =" ./pyproject.toml)
+        script_name=$(grep "^${command} =" ./pyproject.toml || true)
+        if [[ -z ${script_name} ]]; then
+          script_name=$(grep -E "^\s*\"${command}.*=" ./pyproject.toml)
+        fi
+        echo "Script name is: ${script_name}"
+
         if [[  ! $script_name == *':main"' ]]; then
           # the script is not referencing a main function, must be a module
           echo "Validating if ${command} is a valid module command"
@@ -58,10 +67,10 @@ runs:
           echo "Validate if ${main_entry} points to a valid python function"
           python_module=${main_entry%:*}
           function=${main_entry##*:}
-          if [[ -z $main_entry ]]; then
-            echo "Error: Script entry for ${command} not found in [tool.poetry.scripts] section of pyproject.toml "
+          if [[ -z ${main_entry} ]]; then
+            echo "Error: Script entry for ${command} not found in [project.scripts] section of pyproject.toml "
             exit 1
-          fi          
+          fi
         fi
         echo "Static Validation successful!"
 
@@ -99,11 +108,11 @@ runs:
             echo "Success:  test folder was not copied to the Docker"
           fi
           
-          poetry run python -m compileall -q /app || (echo "Error: compileall failed" && exit 1)
+          uv run python -m compileall -q /app || (echo "Error: compileall failed" && exit 1)
           if [[ -z $class  ]];then  
             # function is not null, check if the entry in pyproject.toml scripts is valid
-            entry_valid=$(poetry run python -c "import ${python_module} as module;print( '\''${function}'\''  in dir(module))")
-          elif poetry run python -c "from ${python_module} import ${class};  x=${function};" &> /dev/null; then
+            entry_valid=$(uv run python -c "import ${python_module} as module;print( '\''${function}'\''  in dir(module))")
+          elif uv run python -c "from ${python_module} import ${class};  x=${function};" &> /dev/null; then
             entry_valid=True
           fi
           if [ ! "$entry_valid" == "True" ];then
